### ISSUE TITLE
yarn dev时抛出一个错误TypeError: injection_1.Module is not a function

### ISSUE THREAD

**Issue by wplic2015** [notadd/next#4]
`H:\notadd_project\next\packages\injection\utilities\platform-tools.js:16
            throw err;
            ^

TypeError: injection_1.Module is not a function
    at Object.<anonymous> (H:\notadd_project\next\node_modules\@notadd\cms\cms.injection.js:16:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.load (H:\notadd_project\next\packages\injection\utilities\platform-tools.js:9:28)
    at directories.reduce.filter.map.file (H:\notadd_project\next\packages\injection\utilities\import-injections-from-directories.js:17:57)
[16:32:52] [nodemon] app crashed - waiting for file changes before starting...`

**Comment by wplic2015** [comment]
{
    "name": "notadd-src",
    "version": "2.2.1",
    "author": "notadd",
    "description": "Modern, fast, powerful node.js web framework",
    "main": "index.js",
    "license": "Apache-2.0",
    "scripts": {
        "build": "node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp.js build --dist packages",
        "build:watch": "node --max_old_space_size=4096 ./node_modules/gulp/bin/gulp.js watch --dist packages",
        "dev": "node ./node_modules/gulp/bin/gulp.js --dist packages",
        "fix": "tslint -p tsconfig.json -c tslint.json --fix",
        "prepublish": "npm run build",
        "publish": "node ./node_modules/lerna/bin/lerna.js publish -m \"chore(release): publish %s\"",
        "run:install": "node ./node_modules/@notadd/server/install.js",
        "react-scripts": "./node_modules/.bin/react-scripts",
        "test": "nyc --require ts-node/register mocha src/**/*.spec.ts --reporter spec"
    },
    "dependencies": {
        "pg": "^7.4.3",
        "typescript": "^3.0.1"
    },
    "devDependencies": {
        "@already/webpack-plugins": "^1.0.0",
        "@nestjs/common": "5.1.0",
        "@nestjs/core": "5.1.0",
        "@nestjs/graphql": "^3.0.0",
        "@nestjs/microservices": "5.1.0",
        "@nestjs/swagger": "^2.2.0",
        "@nestjs/testing": "^5.1.0",
        "@nestjs/typeorm": "^5.1.0",
        "@nestjs/websockets": "^5.1.0",
        "@nestjs/cqrs": "^5.1.1",
        "@notadd/addon-local": "~2.1.0",
        "@notadd/authentication": "2.4.4",
        "@notadd/backend": "~2.4.4",
        "@notadd/core": "~2.4.5",
        "@notadd/graphql": "~2.4.5",
        "@notadd/gulp-typescript": "~4.0.2",
        "@notadd/injection": "~2.4.4",
        "@notadd/internationalization": "~2.4.4",
        "@notadd/logger": "~2.4.5",
        "@notadd/server": "~2.4.5",
        "@notadd/setting": "~2.4.5",
        "@notadd/user": "~2.4.6",
        "@notadd/websocket": "~2.4.4",
        "@notadd/workflow": "~2.4.4",
        "@notadd/cms": "~2.0.25",
        "@notadd/i18n":"^2.2.0",
        "@types/autoprefixer": "^6.7.3",
        "@types/cli-color": "^0.3.29",
        "@types/glob": "^5.0.35",
        "@types/graphql-type-json": "^0.1.2",
        "@types/inquirer": "^0.0.36",
        "@types/ip": "^0.0.30",
        "@types/jsonwebtoken": "^7.2.7",
        "@types/load-json-file": "^2.0.7",
        "@types/lodash": "^4.14.108",
        "@types/node": "^9.4.7",
        "@types/passport": "^0.4.5",
        "@types/passport-jwt": "^3.0.1",
        "@types/redis": "^0.12.36",
        "@types/reflect-metadata": "0.0.5",
        "@types/serve-static": "^1.13.2",
        "@types/socket.io": "^1.4.29",
        "@types/tapable": "^1.0.0",
        "@types/webpack": "^4.1.4",
        "@types/webpack-node-externals": "^1.6.3",
        "@types/write-json-file": "^2.2.1",
        "body-parser": "^1.17.2",
        "chalk": "^2.3.0",
        "clang-format": "^1.1.0",
        "gulp": "^3.9.1",
        "gulp-clang-format": "^1.0.23",
        "gulp-nodemon": "^2.2.1",
        "gulp-rename": "^1.2.2",
        "gulp-sequence": "^0.4.6",
        "gulp-sourcemaps": "^2.6.4",
        "gulp-tslint": "^8.1.3",
        "gulp-watch": "^4.3.11",
        "lerna": "^2.5.1",
        "mocha": "^5.1.1",
        "nodemon": "^1.11.0",
        "nyc": "^11.7.2",
        "ts-loader": "^4.2.0",
        "ts-node": "^6.0.3",
        "tslint": "^5.9.1"
    },
    "engines": {
        "node": ">=8.3.0"
    },
    "private": true,
    "workspaces": [
        "packages/authentication",
        "packages/backend",
        "packages/configuration",
        "packages/core",
        "packages/graphql",
        "packages/injection",
        "packages/internationalization",
        "packages/logger",
        "packages/rpc",
        "packages/server",
        "packages/setting",
        "packages/websocket",
        "packages/workflow",
        "packages/i18n",
        "packages/cms",
        "packages/user"
    ]
}

**Comment by zuohuadong** [comment]
此库不再维护，新项目在此发布： https://github.com/notadd/notadd
